export const SET_LOADING = "SET_LOADING"
export const CLEAR_ERROR = "CLEAR_ERROR"
export const SET_ERROR = "CLEAR_ERROR"
export const STOP_LOADING = "STOP_LOADING"
export const GET_TIMESERIES = "GET_TIMESERIES"
export const GET_SECTORS = "GET_SECTORS"
export const GET_STOCK = "GET_STOCK"
export const SET_TICKER = "SET_TICKER"